### ISSUE TITLE
关于不同文章分类插入不同链接的设想

### ISSUE THREAD

**Issue by huangqian8** [r12f/hexo-tag-post-link#3]
考虑到博客文章不同分类（原创和转载），是否可以根据“Front-matter”中的标识来判断文章分类，插入不同的链接？
目前的代码对于原创文章的链接可简化并完美呈现，但对于转载文章还是需重复输入代码，可在“Front-matter”中添加转载标识及原文链接，再生成模板插入。

不熟悉代码的编写，仅是个单纯的想法。

**Comment by r12f** [comment]
多谢反馈，已经添加好了，现在只需要修改```_config.yml```文件就可以对特定category的文章或者包含特定tag的文章添加链接了。

```
post_link:
  per_type_configs:
    - type: category
      name: "category-name"
      insert_before_post: "header-for-category"
      insert_after_post: "footer-for-catefory"
    - type: tag
      name: "tag-name"
      insert_before_post: "header-for-tag"
      insert_after_post: "header-for-tag"
```
